version: '3'
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    build:
      context: ./postgres
      dockerfile: ./dockerfile
    ports:
      - "49154:5432"
    volumes:
      - ./db_data:/docker-entrypoint-initdb.d